# Linear algebra with Numpy 🧠🧠

Some practice exercises are available the [Linear Algebra prepwork](https://app.jedha.co/course/linear-algebra-basics/linear-algebra-exercises).
In this exercise, you will apply what you learnt in the "Numpy and Linear Algebra" to check numerically the answers to these exercises.

In [1]:
import numpy as np

## Operations with vectors and matrices 🤹‍♂️🤹‍♂️

### Vector operations

1. Compute the sum $\vec{u} + \vec{v}$ of the following vectors :
$$
\vec{u} =
\begin{bmatrix}
2 \\
9 \\
-1
\end{bmatrix}
$$
$$
\vec{v} =
\begin{bmatrix}
1 \\
5 \\
3
\end{bmatrix}
$$

In [2]:
u = np.array([2,9,-1])
v = np.array([1,5,3])
w = u+v
display(w)

array([ 3, 14,  2])

2. Compute the difference $\vec{u} - \vec{v}$ between the following vectors :
$$
\vec{u} =
\begin{bmatrix}
10 \\
-2 \\
1
\end{bmatrix}
$$
$$
\vec{v} =
\begin{bmatrix}
4 \\
3 \\
2
\end{bmatrix}
$$

In [3]:
u = np.array([10, -2, 1])
v = np.array([4, 3, 2])
w = u-v
display(w)

array([ 6, -5, -1])

3. Compute : $\alpha (\vec{u} + \vec{v})$ with $\alpha = 4$ and :
$$
\vec{u} =
\begin{bmatrix}
1 \\
-2 \\
2
\end{bmatrix}
$$
$$
\vec{v} =
\begin{bmatrix}
2 \\
1 \\
0
\end{bmatrix}
$$

In [4]:
u = np.array([1, -2, 2])
v = np.array([2, 1, 0])
w = 4 * (u + v)
display(w)

array([12, -4,  8])

4. Compute the norms $\Vert\vec{u}\Vert$ and $\Vert\vec{v}\Vert$ with:
$$
\vec{u}
=
\begin{bmatrix}
1 \\
2 \\
3 \\
4 \\
\end{bmatrix}
$$
$$
\vec{v}
=
\begin{bmatrix}
-1 \\
2 \\
-3 \\
4 \\
\end{bmatrix}
$$

In [5]:
u = np.array([1, 2, 3, 4])
v = np.array([-1, 2, -3, 4])
print(np.linalg.norm(u))
print(np.linalg.norm(v))

5.477225575051661
5.477225575051661


### Matrix operations

5. Compute the sum $A + B$ of the two following matrices :
$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
2 & 1 & 4 \\
3 & 4 & 1
\end{bmatrix}
$$
$$
B =
\begin{bmatrix}
2 & 3 & 4 \\
3 & 2 & 5 \\
4 & 5 & 2
\end{bmatrix}
$$

In [8]:
A = np.array([[1, 2, 3],
              [2, 1, 4],
              [3, 4, 1]])

B = np.array([[2, 3, 4],
              [3, 2, 5],
              [4, 5, 2]])
print("Adiition of A and B: ")
print(A + B)

Adiition of A and B: 
[[3 5 7]
 [5 3 9]
 [7 9 3]]


6. Compute the operation $2A - B$ with:
$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
2 & 1 & 4 \\
3 & 4 & 1
\end{bmatrix}
$$
$$
B =
\begin{bmatrix}
2 & 3 & 4 \\
3 & 2 & 5 \\
4 & 5 & 2
\end{bmatrix}
$$

In [9]:
print("2A-B give: ")
print(2*A - B)

2A-B give: 
[[0 1 2]
 [1 0 3]
 [2 3 0]]


7. Compute the products of matrices : $AB$ and $BA$ with:
$$
A =
\begin{bmatrix}
1 & 0 & 2 \\
2 & 1 & 0 \\
1 & 2 & 1
\end{bmatrix}
$$
$$
B =
\begin{bmatrix}
2 & 0 & 0 \\
1 & 2 & 0 \\
0 & 1 & 2
\end{bmatrix}
$$

In [11]:
A = np.array([[1, 0, 2],
              [2, 1, 0],
              [1, 2, 1]])

B = np.array([[2, 0, 0],
              [1, 2, 0],
              [0, 1, 2 ]])

print("Product AB")
print(A @ B)
print("")

print("Product BA")
print(B @ A)

Product AB
[[2 2 4]
 [5 2 0]
 [4 5 2]]

Product BA
[[2 0 4]
 [5 2 2]
 [4 5 2]]


8. Compute the products of matrices : $AB$ and $BA$ with:
$$
A =
\begin{bmatrix}
1 & 0 \\
2 & 1 \\
1 & 2
\end{bmatrix}
$$
$$
B =
\begin{bmatrix}
2 & 0 & 0 \\
1 & 2 & 0
\end{bmatrix}
$$

In [13]:
A = np.array([[1, 0],
              [2, 1],
              [1, 2]])

B = np.array([[2, 0, 0],
              [1, 2, 0]])
print("Produit AB")
print(A @ B)
print("")

print("Produit BA")
print(B @ A)

Produit AB
[[2 0 0]
 [5 2 0]
 [4 4 0]]

Produit BA
[[2 0]
 [5 2]]


### Matrix-vector product

9. Compute the matrix-vector product $A\vec{v}$ with :
$$
A =
\begin{bmatrix}
1 & 0 & 2 \\
2 & 1 & 0 \\
1 & 2 & 1
\end{bmatrix}
$$
$$
\vec{v} =
\begin{bmatrix}
-1 \\
1 \\
2
\end{bmatrix}
$$

In [15]:
v = np.array([-1, 1, 2])
A =np.array([[1, 0, 2],
             [2, 1, 0],
             [1, 2, 1]])
print("Av is: ")
print(A @ v)

Av is: 
[ 3 -1  3]


## Collinearity and orthogonality 🏌️🏌️

10. Compute the dot product $\vec{u} \cdot \vec{v} $ with:
$$
\vec{u}
=
\begin{bmatrix}
2 \\
-3 \\
-1 \\
\end{bmatrix}
$$
$$
\vec{v}
=
\begin{bmatrix}
3 \\
1 \\
3 \\
\end{bmatrix}
$$

What can you conclude about the angle between the two vectors ?

In [19]:
u_vec = np.array([2, -3, -1])
v_vec = np.array([3, 1, 3])
print("dot product: ", u_vec @ v_vec)

dot product:  0


11. Are $\vec{u}$, $\vec{v}$ collinear ?
$$
\vec{u}
=
\begin{bmatrix}
4 \\
2 \\
-1
\end{bmatrix}
$$

$$
\vec{v}
=
\begin{bmatrix}
-1 \\
-\frac{1}{2} \\
\frac{1}{4}
\end{bmatrix}
$$

In [21]:
u_vec = np.array([4, 2, -1])
v_vec = np.array([-1, -(1/2), (1/4)])
print("uv is: ", u_vec @ v_vec)

u ot v is:  -5.25


12. Are $\vec{u}$, $\vec{v}$ and $\vec{w}$ linearly independent (i.e. there's no relationship of multicolinearity between these vectors) ?
$$
\vec{u}
=
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$$

$$
\vec{v}
=
\begin{bmatrix}
-2 \\
1 \\
\end{bmatrix}
$$

$$
\vec{w}
=
\begin{bmatrix}
-1 \\
3
\end{bmatrix}
$$

In [22]:
print("w-v = u")

w-v = u


## Systems of linear equations 🧩🧩

Consider the following system of linear equations :

$$
\begin{equation}
    \begin{cases}
      2x_1 + x_2 = 2\\
      x_1 + 2x_2 + x_3 = 0 \\
      x_2 + 2x_3 = 1
    \end{cases}
\end{equation}
$$

13. We'd like to write the matrix representation of this system of equations, in the form $A\vec{x} = \vec{c}$ where :
- $A$ is a matrix containing the coefficients of the equation
- $\vec{x}$ is the vector of unknowns
- $\vec{c}$ is a vector of constant values

Create a numpy array corresponding to $A$ and another corresponding to $\vec c$

In [34]:
A = np.array([[2, 1, 0],
              [1, 2, 1],
              [0, 1, 2]])

c_vec = np.array([2, 0, 1])

14. Use numpy to solve the system of equations

In [39]:
A_inv = np.linalg.inv(A)
X_mat =  ((A_inv @ c_vec).round(2))
display(X_mat)

print("We can also do: ")
X = np.linalg.solve(A, c_vec)
print("Solution X is also:", X)

array([ 1.75, -1.5 ,  1.25])

We can also do: 
Solution X is also: [ 1.75 -1.5   1.25]


15. **[Bonus question - for experts only 💪]** Let's use the concept of matrix inverse to solve the system of linear equations !

* Prove that the following matrix is the inverse of matrix $A$ :
$$
B = \begin{bmatrix}
\frac{3}{4} & - \frac{1}{2} & \frac{1}{4} \\
-\frac{1}{2} & 1 & -\frac{1}{2} \\
\frac{1}{4} & -\frac{1}{2} & \frac{3}{4}
\end{bmatrix}
$$

* And then, use $A^{-1}$ to find the solution to the system of equation

In [38]:
B = np.array([[3/4, -1/2, 1/4],
              [-1/2, 1, -1/2],
              [1/4, -1/2, 3/4]])
print(A @ B)
print("")
print(B @ A)
print("")
print(A_inv)
print("")
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]

[[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]


## Matrix diagonalization 🤸🤸

15. Consider the following matrix :

$$
A =
\begin{bmatrix}
3 & -1 \\
2 & 0
\end{bmatrix}
$$

a. Show that $\vec{u} = \begin{bmatrix}1\\1\end{bmatrix}$ and $\vec{v} = \begin{bmatrix}1\\2\end{bmatrix}$ are eigenvectors of $A$

b. What are the eigenvalues associated to $\vec{u}$ and $\vec{v}$ ?

In [42]:
A = np.array([[3, -1],
              [2, 0]])

u = np.array([1, 1])
v = np.array([1, 2])

print("Au: ", A @ u)
print("Av: ", A @ v)
print("------------------------------------------------")

eigenvals, eigenvecs = np.linalg.eig(A)
print("eigenvectors of A: ")
print(eigenvecs)
print("eigenvalues of A: ")
print(eigenvals)

Au:  [2 2]
Av:  [1 2]
------------------------------------------------
eigenvectors of A: 
[[0.70710678 0.4472136 ]
 [0.70710678 0.89442719]]
eigenvalues of A: 
[2. 1.]


We can notice that:
* $A \vec u = 2 \vec u$ which means that $\vec u$ is an eigenvector of $A$ with eigenvalue 2
* $A \vec v = \vec v$ which means that $\vec u$ is an eigenvector of $A$ with eigenvalue 1.