In [72]:
import numpy as np

In [73]:
A = np.array([1,2,3,4,5], dtype=int)
print(A)

[1 2 3 4 5]


In [74]:
B = np.array([1,2,3,4])
print(B.dtype)

int32


In [75]:
C = np.array([[1,2,3], [4,5,6]])
print(C)

[[1 2 3]
 [4 5 6]]


In [76]:
D = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(D)
print(D.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [77]:
vector = np.array([2,3,5])
print(vector)
print("Shape of vector: ", vector.shape)

[2 3 5]
Shape of vector:  (3,)


In [78]:
matrix = np.array([[1,2],
                   [-1,3],
                   [0,4]])
print(matrix)
print("Matrix shape:", matrix.shape)

[[ 1  2]
 [-1  3]
 [ 0  4]]
Matrix shape: (3, 2)


In [79]:
#Vectors operations
u_vec = np.array([6,0,2])
v_vec = np.array([-1,-2,3])
print("vector u: ")
print(u_vec)
print("vector v: ")
print(v_vec)
print()

#perform operations
print("Additon operation: ")
print(u_vec + v_vec)
print()

print("Substraction: ")
print(u_vec - v_vec)
print()

print("Scaling u by factor 3: ")
print(3*u_vec)
print()

print("Multiplication : ")
print(u_vec * v_vec)
print()

#Norm of u
print("Then we will perform the calculation of the norm of u !")
u_norm = ((u_vec[0]**2) + (u_vec[1]**2) + (u_vec[2]**2)) ** (1/2)
print(u_norm)
print()

print("Another way to calculate the norm with the linalg module of numpy !")
print(np.linalg.norm(u_vec)) #we are using the norm function
print()
print("Then we will calculate the norm of v: ")
print("The norm of v is: ", np.linalg.norm(v_vec))
print()

#Dot product of u and v
print("Dot product of u and v")
print(u_vec.dot(v_vec))
print()

vector u: 
[6 0 2]
vector v: 
[-1 -2  3]

Additon operation: 
[ 5 -2  5]

Substraction: 
[ 7  2 -1]

Scaling u by factor 3: 
[18  0  6]

Multiplication : 
[-6  0  6]

Then we will perform the calculation of the norm of u !
6.324555320336759

Another way to calculate the norm with the linalg module of numpy !
6.324555320336759

Then we will calculate the norm of v: 
The norm of v is:  3.7416573867739413

Dot product of u and v
0



Maintenant je ferai des opérations avec les matrices

In [80]:
A_mat = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

B_mat = np.array([[10,10,10],
                  [20,20,20],
                  [30,30,30]])

print("Matrix A: ")
print(A_mat)
print("Matrix B: ")
print(B_mat)
print("--------------------------------------------------------------")
print()

print("Addition: ")
print(A_mat + B_mat)
print()

print("Substraction: ")
print(A_mat - B_mat)
print()

print("Scalling A by a factor 2: ")
print(2 * A_mat)
print()

Matrix A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B: 
[[10 10 10]
 [20 20 20]
 [30 30 30]]
--------------------------------------------------------------

Addition: 
[[11 12 13]
 [24 25 26]
 [37 38 39]]

Substraction: 
[[ -9  -8  -7]
 [-16 -15 -14]
 [-23 -22 -21]]

Scalling A by a factor 2: 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]



Produit de matrices

In [81]:
print(A_mat)
print()
print(B_mat)
print()

print("Matrix product AB with the @ operator")
print(A_mat @ B_mat)
print()
print("Matrix product BA with @")
print(B_mat @ A_mat)
print()
print("AB is not equal to BA")
print()

print("Matrix multiplication with the dot product")
print("Matrix AB with dot")
print(A_mat.dot(B_mat))
print()

print("Matrix BA with dot")
print(B_mat.dot(A_mat))
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 10 10]
 [20 20 20]
 [30 30 30]]

Matrix product AB with the @ operator
[[140 140 140]
 [320 320 320]
 [500 500 500]]

Matrix product BA with @
[[120 150 180]
 [240 300 360]
 [360 450 540]]

AB is not equal to BA

Matrix multiplication with the dot product
Matrix AB with dot
[[140 140 140]
 [320 320 320]
 [500 500 500]]

Matrix BA with dot
[[120 150 180]
 [240 300 360]
 [360 450 540]]



In [82]:
C_mat = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])

x_vec = np.array([5, -2])

print("Taille de la matrice C: ", C_mat.shape)
print()
print("Taille du vecteur x: ", x_vec.shape)
print()

print("Réalisons le produit de cette matrice et de se vecteur: ")

y_vec = C_mat @ x_vec
print("Le produit Cx donne un nouveau vecteur y de taille: ", y_vec.shape)
print(y_vec)

Taille de la matrice C:  (3, 2)

Taille du vecteur x:  (2,)

Réalisons le produit de cette matrice et de se vecteur: 
Le produit Cx donne un nouveau vecteur y de taille:  (3,)
[ 1  7 13]


In [83]:
print("Matrix A: ")
print(A_mat)
print("Transposée de A: ")
print(A_mat.T) # .T permet d'avoir la transposée de A
print()
print("Matrix B: ")
print(B_mat)
print("Transposée de B: ")
print(B_mat.T)
print()

print("Transposée(AB): ")
print((A_mat @ B_mat).T)
print()

print("Transposée(B) @ Transposée(A)")
print((B_mat.T) @ (A_mat.T))

Matrix A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposée de A: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Matrix B: 
[[10 10 10]
 [20 20 20]
 [30 30 30]]
Transposée de B: 
[[10 20 30]
 [10 20 30]
 [10 20 30]]

Transposée(AB): 
[[140 320 500]
 [140 320 500]
 [140 320 500]]

Transposée(B) @ Transposée(A)
[[140 320 500]
 [140 320 500]
 [140 320 500]]


Matrice identité

In [84]:
#déclaration d'une matrice identité d'ordre 3
id_mat  = np.identity(3, dtype='int')
print("Matrice identité I: ")
print(id_mat)
print("matrix A: ")
print(A_mat)
print()

print("IA: ")
print(A_mat @ id_mat)
print()
print("AI: ")
print(id_mat @ A_mat)

Matrice identité I: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
matrix A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

IA: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

AI: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
print("Matrice D: ")
D_mat = np.array([[3,0,2],
                  [2,0,-2],
                  [0,1,1]], dtype= int)
print(D_mat)
print()
print("Inverse de D: ")
D_inv_mat = np.linalg.inv(D_mat )
print(D_inv_mat)
print()

print("Faisons le produit de D par son inverse: ")
print((D_mat @ D_inv_mat).round(2))
print()
print((D_inv_mat @ D_mat).round(2))

Matrice D: 
[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]

Inverse de D: 
[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]

Faisons le produit de D par son inverse: 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]

[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [86]:
U_mat = np.array([[2/3, -2/3, 1/3],
                  [1/3, 2/3, 2/3],
                  [2/3, 1/3, -2/3]])
print("Matrix U")
print(U_mat)
print()

print("Transposée de U")
print(U_mat.T)

print("Produit de U et de U.T")
print((U_mat @ U_mat.T).round(2))

Matrix U
[[ 0.66666667 -0.66666667  0.33333333]
 [ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]

Transposée de U
[[ 0.66666667  0.33333333  0.66666667]
 [-0.66666667  0.66666667  0.33333333]
 [ 0.33333333  0.66666667 -0.66666667]]
Produit de U et de U.T
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Résolution d'une équation avec des matrices pour trouver les inconus x

In [87]:
A_mat = np.array([[1, 2],
                  [3, 9]])
b_vec = np.array([5, 21])
print("Matrix A:")
print(A_mat)
print("Vector b:")
print(b_vec)
print()

## Method 1
print("-- Method 1 --")
# Compute inverse of matrix A
A_mat_inv = np.linalg.inv(A_mat)
# Solve equation
x_vec = A_mat_inv @ b_vec
print("Solution of equation Ax = b:")
print("x = ", x_vec)
print()

## Method 2 : with np.linalg.solve
print("-- Method 2 --")
x_vec = np.linalg.solve(A_mat, b_vec)
print("Solution of equation Ax = b:")
print("x = ", x_vec)

Matrix A:
[[1 2]
 [3 9]]
Vector b:
[ 5 21]

-- Method 1 --
Solution of equation Ax = b:
x =  [1. 2.]

-- Method 2 --
Solution of equation Ax = b:
x =  [1. 2.]


In [88]:
print("Exponentiel de 1: ", np.exp(1))
print("Exponentiel de 0: ", np.exp(0))
print("logarithme népérien de 10: ", np.log(10))
print("Logarithme népérien en base 10 de 10: ", np.log10(10))

Exponentiel de 1:  2.718281828459045
Exponentiel de 0:  1.0
logarithme népérien de 10:  2.302585092994046
Logarithme népérien en base 10 de 10:  1.0


In [89]:
print("Cosinus de 0: ", np.cos(0))
print("Cosinus de pi: ", np.cos(np.pi))
print("Cosinus de pi/2: ", np.cos(np.pi/2).round(2))
print()

print("Sinus de 0: ", np.sin(0))
print("Sinus de pi: ", np.sin(np.pi).round(2))
print("Sinus de pi/2: ", np.sin(np.pi).round(2))
print()

print("tangeante de 0: ", np.tan(0))
print("tangeante de pi: ", np.tan(np.pi).round(2))
print("tangeante de pi/2: ", np.tan(np.pi/2).round(2))


Cosinus de 0:  1.0
Cosinus de pi:  -1.0
Cosinus de pi/2:  0.0

Sinus de 0:  0.0
Sinus de pi:  0.0
Sinus de pi/2:  0.0

tangeante de 0:  0.0
tangeante de pi:  -0.0
tangeante de pi/2:  1.6331239353195368e+16


In [90]:
print("Échantillon de 30 valeurs aléatoires tirées d'une distribution uniforme discrète sur [0, 10]:")
print(np.random.randint(0, 10, 30))


Échantillon de 30 valeurs aléatoires tirées d'une distribution uniforme discrète sur [0, 10]:
[3 0 3 5 0 2 3 8 1 3 3 3 7 0 1 9 9 0 4 7 3 2 7 2 0 0 4 5 5 6]


In [91]:
print("echantillon de 20 nombres aléatoires tirés en de -2 et 2:")
print(np.random.randint(-2, 2, 20))

echantillon de 20 nombres aléatoires tirés en de -2 et 2:
[-2 -2 -1  1 -2 -1  0  0  1 -2 -1 -1  1 -1 -1  1  0  1  1  0]


In [92]:
print("Un exemple de distribution uniforme continue entre 0 et 10:")
print(np.random.uniform(0,10,20))

Un exemple de distribution uniforme continue entre 0 et 10:
[3.58152167 7.50686141 6.07830669 3.25047229 0.38425426 6.34274058
 9.58949269 6.52790317 6.35058874 9.95299568 5.81850329 4.14368588
 4.74697502 6.23510101 3.38007615 6.74752322 3.17201742 7.78345482
 9.49571053 6.62526867]


In [93]:
print("Échantillon de 20 valeurs aléatoires tirées d'une distribution normale de moyenne 5 et standard 2: ")
print(np.random.normal(5, 2, 20))

Échantillon de 20 valeurs aléatoires tirées d'une distribution normale de moyenne 5 et standard 2: 
[5.0537385  7.11167427 4.85363315 3.66855868 4.91177518 4.27346596
 4.97531037 5.08424298 8.91859178 4.60314861 5.66106881 2.12834319
 5.05505663 7.24120931 4.55192244 4.15963322 6.99965939 5.8620683
 3.69817426 2.00251923]


In [94]:
print(np.random.standard_normal(30).round(2))

[-1.23  0.19 -1.   -0.37  1.74  0.59 -0.54 -1.72 -0.58  1.43  0.28  0.79
  0.32  0.7   0.39 -0.04  0.3  -0.43  1.73 -0.87 -0.82 -1.1   0.09  0.46
  0.43  2.07 -0.54 -1.38 -0.49  2.33]


In [95]:
np.random.seed(0)
print(np.random.rand(6))
print(np.random.rand(5))
print(np.random.rand(5))




[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]
[0.43758721 0.891773   0.96366276 0.38344152 0.79172504]
[0.52889492 0.56804456 0.92559664 0.07103606 0.0871293 ]


In [96]:
display(np.zeros((5, 4)))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
display(np.ones((4,5)))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
display((np.ones((2,3,4))))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [99]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [100]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
np.arange(2.2, 4.2, 0.2)

array([2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. ])

In [102]:
def f(x,y):
    return 10*x+y

result = np.fromfunction(f, (5,6), dtype=int)
print(result)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]]


In [117]:
result[0]

array([0, 1, 2, 3, 4, 5])

In [104]:
c = np.array([[  0,  1,  2],
               [ 10, 12, 13],
               [100,101,102],
               [110,112,113]])

for row in c:
    for elt in row:
        print(elt)
print("----------------")

0
1
2
10
12
13
100
101
102
110
112
113
----------------


In [105]:
c = np.array([[  0,  1,  2],
               [ 10, 12, 13],
               [100,101,102],
               [110,112,113]])

for elt in c.flat:
    print(elt)

0
1
2
10
12
13
100
101
102
110
112
113


In [106]:
def f(x, y):
    return 10*x+y

b = np.fromfunction(f, (5,4), dtype=int)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [107]:
print(b[2, 1:3])

[21 22]


In [115]:
a = np.arange(12).reshape(3,4)
display(a)
b = a > 4
b 
a[b]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([ 5,  6,  7,  8,  9, 10, 11])